######################################################################
# Automatically generated by qmake (3.1) Sun Feb 14 14:41:58 2021
######################################################################

#TEMPLATE = subdirs
TEMPLATE = app

# Directories
QT += widgets

SOURCES += \
	main.cpp \
	window.cpp

HEADERS += \
	window.h
